return {
    "nvim-treesitter/nvim-treesitter",
    -- The 'main' branch is a rewrite with a different API: no nvim-treesitter.configs,
    -- and it needs the tree-sitter CLI. Stay on master until this config is migrated.
    branch = "master",
    -- Most parsers ship a pre-generated src/parser.c and just compile. The few that
    -- don't (swift) are generated by master with `tree-sitter generate --no-bindings
    -- --abi 15`, and homebrew's tree-sitter-cli 0.26 removed --no-bindings while 0.24
    -- can't emit ABI 15. If :TSInstall fails on "tree-sitter generate", install the
    -- parser once with a 0.25 CLI in front:
    --   npm install tree-sitter-cli@^0.25.0 --no-save --prefix /tmp/tscli
    --   PATH="/tmp/tscli/node_modules/.bin:$PATH" nvim -c 'TSInstallSync <lang>'
    build = ":TSUpdate",
    config = function()
        local config = require("nvim-treesitter.configs")
        config.setup({
            -- auto install
            auto_install = true,
            -- add language you want to highlight in code
            ensure_installed = {
                "c",
                "lua",
                "vim",
                "javascript",
                "typescript",
                "tsx",
                "html",
                "go",
                "gomod",
                "gowork",
                "gosum",
                "java",
                "json",
                "zig",
                "http",
                "yaml",
                "sql",
                "gotmpl",
                "comment",
                -- xcodebuild.nvim needs this to read Quick-framework test results
                "swift",
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
        })
    end,
}
